{{- if and (not .Values.existingSecret.name) .Values.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sticky-proxy.fullname" . }}
  labels:
    {{- include "sticky-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwtSecret | quote }}
{{- end }}
